name: strax
dependencies:
  - python=3.6
  - numpy
  - scipy
  - matplotlib
  - pandas
  - numba=0.42
  - jupyter
  - jupyterlab
  - tqdm
  - pandoc
  - graphviz
  - nb_conda
  - sphinx
  - astropy
  - holoviews
  - datashader
  - pymongo
  - pytest
  - hypothesis
  - tensorflow
  - keras
  - pip
  - pip:
    - nbsphinx
    - boltons
